version: '3'

services:
    database:
        image: mysql:8.0.22
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=periftech 
        ports:
            - 3306:3306
        networks: 
            - periftech-network
        restart: unless-stopped

    periftech:
        build: .
        image: periftech
        hostname: periftech
        environment:
            - DATABASE_HOST=periftech
            - DATABASE_USER=root
            - DATABASE_PASSWORD=password
            - DATABASE_NAME=periftech
            - DATABASE_PORT=3306
        depends_on:
             - database
        ports:
            - "9091-9095:9090"
        networks:
            - periftech-network
    servicio-interno:
        image: servicio-interno
        ports:
            - 8080:8080   
        networks:
            - periftech-network
    balanceador:
        image: haproxy:1.9.6
        ports: 
            - "8888:80"
        volumes:
            - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
        restart: unless-stopped
        networks:
            - periftech-network

networks:
    periftech-network:
        driver: bridge